
services:
  directus:
    image: directus/directus:10.10.4
    ports:
      - "8055:8055"
    environment:
      KEY: directus_key
      SECRET: directus_secret
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASSWORD: admin1
      DB_CLIENT: sqlite3
      DB_FILENAME: /directus/database/data.db
    volumes:
      - directus_db:/directus/database
      
volumes:
  directus_db:
